# fly.toml app configuration file generated for lineageos-updater-backend on 2023-05-23T20:41:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lineageos-updater-backend"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  CACHE_REDIS_HOST = "localhost"
  CACHE_TYPE = "RedisCache"
  UPSTREAM_URL = "https://mirrorbits.lineageos.org/api/v2/builds"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 450

[metrics]
  port = 8080
  path = "/metrics"
